[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Tipping pathways"
authors = [{name = "Naud Loomans", email = "n.loomans@tue.nl"}]
dynamic = ["version", "description"]
